# Generated by Django 2.2.3 on 2020-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCategoria',
            fields=[
                ('idcolaborador_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'auth_categoria',
                'managed': False,
            },
        ),
    ]
