# Generated by Django 2.2.3 on 2020-05-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('codigo', models.CharField(max_length=6)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=256)),
                ('area_sap', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=150, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('zestado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('cliente', models.CharField(max_length=35)),
                ('descripcion', models.CharField(blank=True, max_length=75, null=True)),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('zestado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogDeModificaciones',
            fields=[
                ('idlog_de_modificaciones', models.AutoField(primary_key=True, serialize=False)),
                ('id_entidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_modificacion', models.CharField(max_length=1)),
                ('campo_modificado', models.CharField(blank=True, max_length=25, null=True)),
                ('anterior_valor', models.CharField(blank=True, max_length=55, null=True)),
                ('log', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'log_de_modificaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModulosSap',
            fields=[
                ('idmodulos_sap', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('modulo', models.CharField(max_length=45)),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'modulos_sap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=3)),
                ('pais', models.CharField(max_length=25)),
                ('codigo_tel', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('idpeticion', models.AutoField(primary_key=True, serialize=False)),
                ('id_pet_fenix', models.CharField(max_length=7)),
                ('id_ot_fenix', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_fin_acuerdo', models.DateField()),
                ('fecha_real_entrega', models.DateField()),
                ('horas_acuerdo', models.FloatField()),
                ('horas_estimadas', models.FloatField()),
                ('comentario', models.CharField(blank=True, max_length=75, null=True)),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('zestado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'peticion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeticionEstado',
            fields=[
                ('idestado_peticion', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=15)),
                ('codigo', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=45)),
                ('descripcion_fenix', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'peticion_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeticionGestion',
            fields=[
                ('idgestion_peticion', models.AutoField(primary_key=True, serialize=False)),
                ('gestion', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'peticion_gestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeticionTipo',
            fields=[
                ('idtipo_peticion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('ultima_modificacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peticion_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqCalidadInput',
            fields=[
                ('idreq_calidad_input', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=1)),
                ('calidad', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'req_calidad_input',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqComentarios',
            fields=[
                ('idreq_comentarios', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'req_comentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqContacto',
            fields=[
                ('idpeticion_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('celular', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'req_contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqEstado',
            fields=[
                ('idreq_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)), 
            ],
            options={
                'db_table': 'req_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqEstimAltoNivel',
            fields=[
                ('idreq_estim_alto_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=1)),
                ('nivel', models.CharField(max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'req_estim_alto_nivel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqPrioridad',
            fields=[
                ('idreq_prioridad', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.CharField(max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'req_prioridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('idrequerimiento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=11)),
                ('codigo_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('breve_descripcion', models.CharField(max_length=75)),
                ('fecha_estimacion', models.DateField()),
                ('fecha_inicio_planificada', models.DateField()),
                ('fehca_inicio_real', models.DateField()),
                ('fecha_fin_planificada', models.DateField()),
                ('fecha_entrega_real', models.DateField()),
                ('estimacion_acuerdo', models.FloatField(blank=True, null=True)),
                ('estimacion_fenix_h', models.FloatField()),
                ('etc', models.FloatField(blank=True, null=True)),
                ('horas_adicionales', models.FloatField(blank=True, null=True)),
                ('horas_acuerddo_mes', models.FloatField(blank=True, null=True)),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('zestado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'requerimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('idriesgo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5)),
                ('fecha_indentificacion', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('acciones', models.CharField(blank=True, max_length=75, null=True)),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('zestado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'riesgo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiesgoCategoria',
            fields=[
                ('idriesgo_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'riesgo_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiesgoEstado',
            fields=[
                ('idestado_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=15)),
                ('desccripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'riesgo_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiesgoResolucion',
            fields=[
                ('idriesgo_resolucion', models.AutoField(primary_key=True, serialize=False)),
                ('resolucion', models.CharField(max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'riesgo_resolucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiesgoSeguimiento',
            fields=[
                ('idriesgo_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'riesgo_seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiesgoTipo',
            fields=[
                ('idtipo_riesgo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'riesgo_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('idtask', models.AutoField(primary_key=True, serialize=False)),
                ('id_interno', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=150)),
                ('subtarea', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('esfuerzo_total_estandar', models.FloatField()),
                ('esfuerzo_ejecutado', models.FloatField()),
                ('etc', models.FloatField(blank=True, null=True)),
                ('subida_a_fenix', models.CharField(blank=True, max_length=1, null=True)),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('zestado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskEstado',
            fields=[
                ('idtask_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'task_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskFaseActividad',
            fields=[
                ('idtask_fase_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('id_interno', models.CharField(blank=True, max_length=6, null=True)),
                ('tipo', models.CharField(max_length=6)),
                ('codigo', models.CharField(max_length=3)),
                ('fase_actividad', models.CharField(max_length=25)),
                ('esfuerzo', models.FloatField()),
                ('parte_esfuerzo_sin_gestion', models.FloatField()),
                ('parte_esfuerzo', models.FloatField()),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('zestado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'task_fase_actividad',
                'managed': False,
            },
        ),
    ]
