# Generated by Django 2.1 on 2020-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('alias', models.CharField(blank=True, max_length=30, null=True)),
                ('area_sap', models.CharField(choices=[('ABAP', 'ABAP'), ('FUNCIONAL', 'FUNCIONAL')], max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], max_length=1, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=150, null=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('zestado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
    ]
