# Generated by Django 2.1 on 2020-05-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColCategoria',
            fields=[
                ('idcolaborador_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('variable', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'col_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requerimientos',
            fields=[
                ('idrequerimiento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=11)),
                ('requerimien_asociado', models.IntegerField(blank=True, null=True)),
                ('codigo_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('breve_descripcion', models.CharField(max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=75, null=True)),
                ('fecha_estimacion', models.DateField()),
                ('fecha_inicio_planificada', models.DateField()),
                ('fehca_inicio_real', models.DateField()),
                ('fecha_fin_planificada', models.DateField()),
                ('fecha_entrega_real', models.DateField()),
                ('estimacion_acuerdo', models.FloatField(blank=True, null=True)),
                ('estimacion_fenix_h', models.FloatField()),
                ('etc', models.FloatField(blank=True, null=True)),
                ('horas_adicionales', models.FloatField(blank=True, null=True)),
                ('horas_acuerddo_mes', models.FloatField(blank=True, null=True)),
                ('seguimiento_diario', models.TextField(blank=True, null=True)),
                ('zultima_modificacion', models.DateField(blank=True, null=True)),
                ('zestado', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'requerimientos',
                'managed': False,
            },
        ),
    ]
