# Generated by Django 2.1 on 2020-05-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_gant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GantDetalle',
            fields=[
                ('idgat_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('semana', models.IntegerField()),
                ('cod_req', models.CharField(max_length=15)),
                ('horas', models.FloatField()),
            ],
            options={
                'db_table': 'gant_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GantResumen',
            fields=[
                ('idgant_resumen', models.AutoField(primary_key=True, serialize=False)),
                ('hac_sem_uno', models.FloatField(blank=True, null=True)),
                ('inc_sem_uno', models.FloatField(blank=True, null=True)),
                ('dis_sem_uno', models.FloatField(blank=True, null=True)),
                ('hac_sem_dos', models.FloatField(blank=True, null=True)),
                ('inc_sem_dos', models.FloatField(blank=True, null=True)),
                ('dis_sem_dos', models.FloatField(blank=True, null=True)),
                ('hac_sem_tres', models.FloatField(blank=True, null=True)),
                ('inc_sem_tres', models.FloatField(blank=True, null=True)),
                ('dis_sem_tres', models.FloatField(blank=True, null=True)),
                ('hac_sem_cuatro', models.FloatField(blank=True, null=True)),
                ('inc_sem_cuatro', models.FloatField(blank=True, null=True)),
                ('dis_sem_cuatro', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gant_resumen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gants',
            fields=[
                ('idgants', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.DateField()),
                ('fech_creacion', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'gants',
                'managed': False,
            },
        ),
    ]
