# Generated by Django 2.1 on 2020-05-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_gantdetalle_gantresumen_gants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('iddominio', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'dominio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idequipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
    ]
