# Generated by Django 2.1 on 2020-05-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_dominio_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False, 'permissions': (('es_managerr', 'Managerr'), ('es_liderr', 'Liderr'))},
        ),
    ]
