# Generated by Django 2.1 on 2020-05-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20200526_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False, 'permissions': (('es_manager', 'MANAGER'), ('es_lider', 'LEADER'))},
        ),
    ]
