# Generated by Django 2.1 on 2020-05-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20200526_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('idincidencia', models.AutoField(primary_key=True, serialize=False)),
                ('num_bug', models.CharField(max_length=15)),
                ('descripción', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=1)),
                ('criticidad', models.CharField(max_length=1)),
                ('fecha_ident', models.DateField()),
                ('categoria_inc', models.CharField(max_length=1)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_inc_car', models.CharField(max_length=1)),
                ('esfuerzo', models.FloatField(blank=True, null=True)),
                ('comentario_car', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'incidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncLocalizadaEn',
            fields=[
                ('idinc_localizada_en', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'inc_localizada_en',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncTipo',
            fields=[
                ('idinc_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'inc_tipo',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False, 'permissions': (('es_manager', 'MANAGER'), ('es_leader', 'LEADER'))},
        ),
    ]
