# Generated by Django 2.1 on 2022-11-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_authcliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquiDetalle',
            fields=[
                ('idequi_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('creado_el', models.DateField()),
                ('valido_desde', models.DateField(blank=True, null=True)),
                ('valido_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, default='1', max_length=1, null=True)),
            ],
            options={
                'db_table': 'equi_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstDetalle',
            fields=[
                ('id_est_det', models.AutoField(primary_key=True, serialize=False)),
                ('esfuerzo', models.FloatField()),
                ('peso', models.FloatField()),
                ('creador', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('ajus_cantidad', models.FloatField(blank=True, null=True)),
                ('ajus_descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('ajus_fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'est_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstimPeso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('peso_hist', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('alta', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'estim_peso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hardcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=5)),
                ('asp', models.CharField(max_length=5)),
                ('typcon', models.CharField(max_length=5)),
                ('consum', models.CharField(max_length=5)),
                ('item', models.CharField(blank=True, max_length=10, null=True)),
                ('val01', models.CharField(max_length=100)),
                ('val02', models.CharField(blank=True, max_length=100, null=True)),
                ('val03', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hardcode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('idperer', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=35)),
                ('resultado', models.CharField(choices=[('1', 'OK'), ('2', 'KO'), ('3', 'N/A')], default='1', max_length=1)),
                ('version', models.IntegerField()),
                ('nota', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peer_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeticionInputFinal',
            fields=[
                ('idpet_inp_fnl', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=1)),
                ('input_final', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'peticion_input_final',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqCriticidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criticidad', models.CharField(max_length=15)),
                ('crit', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'req_criticidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqInputFinal',
            fields=[
                ('idreq_input_final', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=1)),
                ('input_final', models.CharField(max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'req_input_final',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zdificultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad', models.CharField(max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('alta', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'zdificultad',
                'managed': False,
            },
        ),
    ]
