# Generated by Django 2.1 on 2022-11-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CliRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.CharField(max_length=4)),
                ('clie', models.CharField(max_length=100)),
                ('fd1', models.CharField(max_length=10)),
                ('fh1', models.CharField(max_length=10)),
                ('resu', models.CharField(max_length=300)),
                ('pet_hac', models.FloatField()),
                ('estm_esf', models.FloatField()),
                ('req_hac', models.FloatField()),
                ('tsk_eje', models.FloatField()),
                ('gnt_inc', models.FloatField()),
                ('etc', models.FloatField()),
            ],
        ),
    ]
